### ISSUE TITLE
Feature Request: Playing POE On Second Monitor

### ISSUE THREAD

**Issue by tojurnru** [notablackbear/poe_qolV2#10]
As titled, is it possible to make it able to support playing POE on second monitor? The main reason I play POE on second monitor is because windows taskbar on second monitor sucks - it only provide limited information compared to the taskbar on main monitor. If I were to play POE on main monitor windows fullscreen, the main taskbar will be hidden.

Would be happy to do a pull request if the code is open sourced.

**Comment by notablackbear** [comment]
Thanks for the suggestion. As things are right now, this would be a huge challenge. This is due to the design of the original program. I don't plan on making this change, sorry. Perhaps in a future re-work this could be possible. 

I believe there is a way to move the main taskbar to the second monitor in Windows 10. [Maybe this could work.](https://www.thewindowsclub.com/move-taskbar-to-second-monitor-on-windows)
