### ISSUE TITLE
Windows Security flagging the exe

### ISSUE THREAD

**Issue by projectsix84** [notablackbear/poe_qolV2#30]
When I unzip the contents, Windows Security is popping up with a warning flagging the exe with this and marking it as severe: 

Trojan:Win32/Emali.A!cl

Any idea what that is about?

**Comment by chaosprinz** [comment]
Same as bashmydrain here. 
As its throwing its error since today, i think it came with the last defender-update. Used it until yester without any issue. 

![poe_qolV2_defenderWarn](https://user-images.githubusercontent.com/322697/93805008-5fe5e180-fc47-11ea-86da-28811a876db9.PNG)

Some clarification would be nice. Is there source-code for the exe laying around anywhere ?

**Comment by notablackbear** [comment]
see #44 . This is a false positive some people are getting.
