### ISSUE TITLE
Does not work on second monitor.

### ISSUE THREAD

**Issue by chrisabos** [notablackbear/poe_qolV2#38]
If POE is open on my second monitor and try to use the QOL Filters in my stash tabs.. it will move the mouse the my first monitor and click over there instead of the game.

**Comment by notablackbear** [comment]
Hi, no this won't work if you are running PoE on the non-Primary monitor as is documented in the Setup file. They way it is currently setup, it would be difficult to change this. I don't plan to put so much effort into this since most users can run PoE on their primary. This could be addressed when/if I get to re-doing the code from scratch so it can be open sourced. Sorry.
