### ISSUE TITLE
windows trojan alert

### ISSUE THREAD

**Issue by AngeloMerlo** [notablackbear/poe_qolV2#49]
when i open the executable windows 10 shows me an alert that contains a trojan in the file and moves it to quarantine automatically.

**Comment by jeanpaim** [comment]
Yes!! my windows 10 alerts a trojan..... the staff can explain this?

**Comment by jbitely** [comment]
https://www.virustotal.com/gui/file/7f34753a850aa75d0e66974bf14c018b468190e51966fcfaabf64234f4280687/detection

**Comment by jeanpaim** [comment]
> https://www.virustotal.com/gui/file/7f34753a850aa75d0e66974bf14c018b468190e51966fcfaabf64234f4280687/detection

I'm sorry, but I don't understand what this site means. I only know that it accuses Trojan in the file. Could you explain the danger level of this trojan better?

**Comment by notablackbear** [comment]
I don't know why this is happening for some people but not others. I am not a software security expert. The hisotry of source has been released with the owner's permission under the `archive` branch if you'd like to verify the security. The project will be open source from here forward also. Otherwise, I'd just say to ignore the alert.
