### ISSUE TITLE
Do you intend to open the .exe source code?

### ISSUE THREAD

**Issue by mmsilveira** [notablackbear/poe_qolV2#7]
I think it is interesting for users to know how this app works.

**Comment by hkalic** [comment]
> I think it is interesting for users to know how this app works.

... and for security reasons.

TY

**Comment by Gikona** [comment]
The original coder still has not given his OK to release the source code, AFAIK.

**Comment by notablackbear** [comment]
I 100% understand this request, and this is addressed in the first lines of the Readme. Right now, we want to get consent from all contributors and give them enough time to respons. The choice was between not sharing with the community until after league start or as is. Since the chaos recipe is only profitable for a short window after league start, we decided to offer the option for players to make. 

I definitely want to release the source in the future, but think its fair to give other contributors ample time to consent before doing so.

**Comment by cannonpalms** [comment]
Where was the original version hosted? Did it include a license? I’m guessing not.

**Comment by notablackbear** [comment]
The code owner, Path of Matth, has decided to release the source. Additionally it has already been decompiled by many users at this point anyway, to verify security.
